---
accent_color: "#7A5A3A"
lang: en-US
title: CoffeeTrace
description: An ecosystem of Coffee Plantations, Farmer, Collectives, Processors and
  Brands
baseurl: ''
url: https://blog.coffeetrace.io
permalink: "/:title"
favicon: "/images/favicon-128.png"
google_analytics: ''
disqus: coffeetrace
navigation:
- text: Blog
  url: "/"
- text: About
  url: "/about/"
- text: Tags
  url: "/tags/"
- text: Download
  url: https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme
footer:
  content: "© [AgriYoda](https://agriyoda.com) all rights reserved."
  has_social: true
plugins:
- jekyll-paginate
paginate: 3
paginate_path: "/page:num/"
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
