---
accent_color: "#71563E"
lang: en-US
title: CoffeeTrace
description: An ecosystem of Coffee Plantations, Farmer, Collectives, Processors and
  Brands
baseurl: ''
url: https://coffeetraceblog.netlify.com
permalink: "/:title"
favicon: "/images/favicon-128.png"
google_analytics: ''
disqus: coffeetrace
navigation:
- text: Blog
  url: "/"
- text: About
  url: "/about/"
- text: Style Guide
  url: "/style-guide/"
- text: Tags
  url: "/tags/"
- text: Download
  url: https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme
footer:
  content: "&copy; Scriptor all rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true
plugins:
- jekyll-paginate
paginate: 3
paginate_path: "/page:num/"
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
